runtime: python38

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /question
    script: auto

  - url: /question/.*
    script: auto

  - url: /
    static_dir: dist
